### ISSUE TITLE
support for imputed data

### ISSUE THREAD

**Issue by ghost** [OpenMendel/OrdinalGWAS.jl#10]
Hi, 

Thanks for this nice package.
I wonder whether this only supports for best-guess data in .bed format. Does it also support for imputed data containing dosage information. like .bgen or .pgen?

Best

**Comment by chris-german** [comment]
Hi,

Thanks for the question. Currently the code is implemented to only support PLINK format. We are going to add VCF format in the near future. We hope to add support for .bgen format as well, since that's a very popular imputed format, there are just currently not tools available to read .bgen files into Julia, so it will take a bit more effort.

**Comment by chris-german** [comment]
Hi @wodehezi666 , 

We are still working on .bgen support, but VCF files (with dosages) are now supported in v0.4.0.

**Comment by ghost** [comment]
Hi Chris,
Superb! 
I will give it a try to run the analysis in VCF.

Best,
Song
