### ISSUE TITLE
test data for proportional odds assumption

### ISSUE THREAD

**Issue by lisongmiller** [OpenMendel/OrdinalGWAS.jl#11]
Hi there,

Actually, I have some questions about the statistical method in this tool and your paper(DOI: 10.1002/gepi.22276). I hope it is okay to just post here.

1. In your paper, the first analysis is done by using simulated data, which is generated by proportional odds assumption. So for later analysis using COPDGene or UKB, did you also check whether these data follow proportional odds assumption before performing analysis? Do we also need to check this for our own data? Or it is okay to just run the ordinal analysis directly because it is difficult to check proportional odds assumption for real data and adding several covariates and large sample size may break the proportional odds assumption.  

2. I am quite a newbie in statistics, I am lost in the math part of your paper. please forgive me for this silly question. Is the statistical model in your tool the same as proportional odds model? Are there any differences? 

Best,
Song

**Comment by chris-german** [comment]
Hi Song,

Thanks for the questions. 

> In your paper, the first analysis is done by using simulated data, which is generated by proportional odds assumption. So for later analysis using COPDGene or UKB, did you also check whether these data follow proportional odds assumption before performing analysis? Do we also need to check this for our own data? Or it is okay to just run the ordinal analysis directly because it is difficult to check proportional odds assumption for real data and adding several covariates and large sample size may break the proportional odds assumption.

We did not check the PO assumption for the real data analyses because the sample sizes and number of covariates are large. In the paper we state that the current tests for the proportional odds assumption are described as very liberal, often leading to rejection when there are many parameters in the model or the sample size is large. It's possible to check it using some existing software such as SAS, but if your data is not small it's likely it will be rejected. The PO assumption basically states that the odds of being in one grouping vs another  ({mild} vs {medium, severe}) is proportional to the odds of other groups ({mild, medium} vs {severe}). In simulation scenarios, generating data that violated the PO assumption gave us an effect estimate that was a weighted mean of the effects for the (log) odds of the different groupings. This can lead to an incorrect estimate of the effect size, but we didn't find a scenario where it led to increased type I error, often just decreased power, so we weren't too worried when it comes to reporting signals found. 

> I am quite a newbie in statistics, I am lost in the math part of your paper. please forgive me for this silly question. Is the statistical model in your tool the same as proportional odds model? Are there any differences?

No worries, it is a good question. The model for OrdinalGWAS.jl is an ordered multinomial model. It **is** the proportional odds model when the link function is the logit link (default link function used in the package). Table 1 in the paper gives other link functions that can be used and the corresponding model, such as the ordered probit model (probit link).

**Comment by lisongmiller** [comment]
Hi Chris,

Thanks for your quick response. That's very clear now.
